// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMsD5WbZL9jjNmVEmydfLlQsJWOntIgOs',
    appId: '1:949217406720:web:7e77e90b688bc6097d4de5',
    messagingSenderId: '949217406720',
    projectId: 'mahjong-app-34b1a',
    authDomain: 'mahjong-app-34b1a.firebaseapp.com',
    storageBucket: 'mahjong-app-34b1a.firebasestorage.app',
    measurementId: 'G-RW92KQEFQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9DF6WBjASgi91-p0XmYcDN40hcEwm3D8',
    appId: '1:949217406720:android:86938d028b66cfe57d4de5',
    messagingSenderId: '949217406720',
    projectId: 'mahjong-app-34b1a',
    storageBucket: 'mahjong-app-34b1a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3L-Qrf8Klh5ApBWHeg--0ob76KAKdm64',
    appId: '1:949217406720:ios:798eea2e6649e5b07d4de5',
    messagingSenderId: '949217406720',
    projectId: 'mahjong-app-34b1a',
    storageBucket: 'mahjong-app-34b1a.firebasestorage.app',
    iosBundleId: 'com.example.mahjongApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD3L-Qrf8Klh5ApBWHeg--0ob76KAKdm64',
    appId: '1:949217406720:ios:798eea2e6649e5b07d4de5',
    messagingSenderId: '949217406720',
    projectId: 'mahjong-app-34b1a',
    storageBucket: 'mahjong-app-34b1a.firebasestorage.app',
    iosBundleId: 'com.example.mahjongApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMsD5WbZL9jjNmVEmydfLlQsJWOntIgOs',
    appId: '1:949217406720:web:ff078fd1cfab54dd7d4de5',
    messagingSenderId: '949217406720',
    projectId: 'mahjong-app-34b1a',
    authDomain: 'mahjong-app-34b1a.firebaseapp.com',
    storageBucket: 'mahjong-app-34b1a.firebasestorage.app',
    measurementId: 'G-S4VB43XGMK',
  );
}
